contract = (
    ('CT', 'CONTRATO'),
    ('NO', 'NOMBRAMIENTO'),
)

dedication = (
    ('TM', 'MEDIO TIEMPO'),
    ('TP', 'TIEMPO PARCIAL'),
    ('TC', 'TIEMPO COMPLETO'),
)

position = (
    ('OCSEX', 'PROFESOR OCASIONAL SEMI EXCLUSIVA'),
    ('OCEX', 'PROFESOR OCASIONAL EXCLUSIVA'),
    ('AUX', 'AUXILIAR PROFESOR AUXILIAR'),
    ('PRN', 'PRINCIPAL PROFESOR PRINCIPAL'),
    ('AGP', 'AGREGADO PROFESOR AGREGADO'),
    ('TECUSEX', 'TECNICO DOCENTE UNIVERSITARIO SEMI EXCLUSIVA'),
    ('TECUEX', 'TECNICO DOCENTE UNIVERSITARIO EXCLUSIVA'),
)
