# Generated by Django 3.2.4 on 2021-10-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(db_column='imagen', default='', max_length=300, upload_to='images/eva/'),
        ),
    ]
