# Generated by Django 3.2.4 on 2021-10-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0002_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosgeneral',
            name='value',
            field=models.DecimalField(db_column='valor', decimal_places=2, default=0, max_digits=5),
        ),
    ]
